@scheme = http
@hostname = localhost
@port = 7000
@host = {{hostname}}:{{port}}
@baseUrl = {{scheme}}://{{host}}
@json = application/json

### CREATE PRODUCT 
# @name newproduct
POST {{baseUrl}}/product
Content-Type: {{json}}

{
    "name": "product",
    "price": 0.09
}

@prodID = {{newproduct.response.body.$.id}}

### LIST PRODUCT
GET {{baseUrl}}/product/{{prodID}}

### LIST PRODUCTS
GET {{baseUrl}}/product

### UPDATE PRODUCT
PUT {{baseUrl}}/product/{{prodID}}
Content-Type: {{json}}

{   
    "name": "t-shirt2",
    "price": 20.06
}

### DELETE PRODUCT
DELETE {{baseUrl}}/product/{{prodID}}

### UPDATE PRODUCT WITH INCORRECT BODY
PUT {{baseUrl}}/product/{{prodID}}
Content-Type: {{json}}

{   
    "price": "book",
    "email": 234,
    "name": 123
}

### CREATE PRODUCT WITH INCORRECT BODY
POST {{baseUrl}}/product
Content-Type: {{json}}

{   
    "email": 234,
    "name": '123',
    "price": "book",
    "name": 123
}


### CREATE PRODUCT WITH EXTRA FIELD BODY
POST {{baseUrl}}/product
Content-Type: {{json}}

{   
    "email": 234,
    "price": 123,
    "name": "abc"
}
