@scheme = http
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@baseUrl = {{scheme}}://{{host}}
@apiBase = {{baseUrl}}/v1
@json = application/json

### CREATE PRODUCT
# @name newproduct
POST {{apiBase}}/product
Content-Type: {{json}}

{
    "name": "product",
    "stock": 10,
    "price": {
        "minorAmount": 9,
        "currency": "PLN"
    }
}

@prodID = {{newproduct.response.body.$.id}}

### LIST PRODUCT
GET {{apiBase}}/product/{{prodID}}

### LIST PRODUCTS
GET {{apiBase}}/product

### LIST PRODUCTS (keyset paginated)
# next page: copy `nextCursor` from the response into the cursor query param
GET {{apiBase}}/product?limit=10&cursor=

### UPDATE PRODUCT
PUT {{apiBase}}/product/{{prodID}}
Content-Type: {{json}}

{   
    "name": "t-shirt2",
    "price": {
        "minorAmount": 2006,
        "currency": "PLN"
    }
}

### PURCHASE PRODUCT
POST {{apiBase}}/product/{{prodID}}/purchase
Content-Type: {{json}}

{
    "quantity": 2
}

### DELETE PRODUCT
DELETE {{apiBase}}/product/{{prodID}}

### UPDATE PRODUCT WITH INCORRECT BODY
PUT {{apiBase}}/product/{{prodID}}
Content-Type: {{json}}

{   
    "price": "book",
    "email": 234,
    "name": 123
}

### CREATE PRODUCT WITH INCORRECT BODY
POST {{apiBase}}/product
Content-Type: {{json}}

{   
    "email": 234,
    "name": '123',
    "price": "book",
    "name": 123
}


### CREATE PRODUCT WITH EXTRA FIELD BODY
POST {{apiBase}}/product
Content-Type: {{json}}

{   
    "email": 234,
    "price": {
        "minorAmount": 123,
        "currency": "PLN"
    },
    "name": "abc"
}
